server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      #限制上传文件的大小
      max-file-size: 10MB
      max-request-size: 10MB

dubbo:
  application:
    name: back_web
  registry:
    address: zookeeper://120.25.244.38:2181
  consumer:
    check: false
  protocol:
    port: -1
    name: dubbo

upload:
  path: F:/dev/
fdfs:
  connect-timeout: 10000
  so-timeout: 10000
  tracker-list:
    - 120.25.244.38:22122
  thumb-image:
    height: 100
    width: 100
  pool:
    jmx-enabled: false
