
server:
  port: 8082
dubbo:
  application:
    name: search_web
  registry:
    address: zookeeper://120.25.244.38:2181
  consumer:
    check: false
    timeout: 10000
    retries: 3
     .
spring:
  thymeleaf:
    cache: false
