spring:
  datasource:
    url: jdbc:mysql:///1903_shop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 120.25.244.38
    virtual-host: /
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://120.25.244.38:2181
  protocol:
    port: -1
    name: dubbo
  consumer:
    check: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

upload:
  path: E:/dev/