
spring:
  datasource:
    url: jdbc:mysql:///1903_shop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://120.25.244.38:2181
  protocol:
    port: -1

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
